USE [DWH_PROJECT]
GO

/****** Object:  Table DimensionProduct    Script Date: 31/05/2023 16:27:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DimProduct(
	ProductID [int] NOT NULL,
	ProductName [varchar](255) NOT NULL,
	ProductCategory [varchar](255) NOT NULL,
	ProductUnitPrice [int] NULL,
 CONSTRAINT PKProdut PRIMARY KEY CLUSTERED 
(
	ProductID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


