USE [DWH_PROJECT]
GO

/****** Object:  Table DimensionStatusOrder    Script Date: 31/05/2023 16:30:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE DimStatusOrder(
	StatusID [int] NOT NULL,
	StatusOrder [varchar](50) NOT NULL,
	StatusOrderDesc [varchar](50) NOT NULL,
 CONSTRAINT PKStatusOrder PRIMARY KEY CLUSTERED 
(
	StatusID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


